= OSX Notes
:author: jonny rhea
:doctype: notes
:encoding: utf-8
:lang: en
:toc: left
:published_at: 2013-12-06
:numbered:

[index]
== Create a bootable debian usb drive

download a debian iso and then convert iso to dmg:
----
hdiutil convert -format UDRW -o debian.img debian-7.2.0-amd64-netinst.iso
----

list devices and find usb drive:
----
diskutil list
----

parition usb drive:
----
diskutil partitionDisk /dev/disk4 1 "Free Space" "unused" "100%"
----

copy dmg to usb drive:
----
sudo dd if=debian.img.dmg of=/dev/disk4 bs=1m
----

eject disk:
----
diskutil eject /dev/disk4
----

[index]
== SSH

stop ssh server:
----
sudo launchctl stop com.openssh.sshd
----

start ssh server:
----
sudo launchctl start com.openssh.sshd
----

[index]
== Terminal App

=== SSH Session: Page Up/Down and Home/End
Menu Bar -> Terminal -> Preferences -> Profile Tab +
- Select your current Settings theme +
- Click the Keyboard tab: +
  Edit (or Add) the entry for Home: +
    Action: Send Text +
    String: \001 (or press Ctrl+a) +
  Edit (or Add) the entry for End: +
    Action: Send Text +
    String: \005 (or press Ctrl+e) +
  Edit (or Add) the entry for Page Up: +
    Action: Send Text +
    String: \033[5~ +
  Edit (or Add) the entry for Page Down: +
    Action: Send Text +
    String: \033[6~ +
- Close the settings window. +


[index]
== X11 Forwarding

We need an X.Org X Windowing System for OSX: 
----
wget -c https://xquartz-dl.macosforge.org/SL/XQuartz-2.7.8.dmg
----

/etc/sshd_config

change:
----
#X11Forwarding no
----

to:

----
X11Forwarding yes
----

Create ~/.ssh/config:
----
host *
ForwardX11 yes
ForwardX11Trusted yes
XauthLocation /opt/X11/bin/xauth
----