= Cryptocurrency Notes
:author: jonny rhea
:doctype: notes
:encoding: utf-8
:lang: en
:toc: left
:published_at: 2013-11-12
:numbered:

[index]
== Mining
=== Bitcoin

TODO: import old notes

=== Altcoins

TODO: import old notes

=== Ethereum Mining Setup

I opted to update the OS on my old rigs that used to mine Scrypt/Scrypt-N coins.  Probably wasn't the easiest route, but you never learn anything if nothing goes wrong!  Remember kids, this is supposed to be fun!

==== Update to Xubuntu 14.04

Updated old alt coin mining rig from Xubuntu 12.10 to 13.10

Update /etc/apt/sources.list to EOL sources list:
----
## EOL upgrade sources.list
deb http://old-releases.ubuntu.com/ubuntu/ quantal main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ quantal-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ quantal-security main restricted universe multiverse
----

Installed aptitude:
----
sudo apt-get install aptitude
----

install update manager packages (might already be there):
----
sudo aptitude install update-manager-core update-manager
----

double check desktop package name (should be obvious considerin I am running Xubuntu:
----
dpkg -l | grep tu-desktop
----

installing xubuntu desktop:
----
sudo aptitude install xubuntu-desktop
----

now upgrade:
----
sudo apt-get update
sudo apt-get dist-upgrade
sudo do-release-upgrade
----

Then upgraded to 14.04 so I could use the Ethereum PPAs

==== Build Geth

Download the latest Go:
----
curl -O https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
----

Unpack:
----
tar -C /usr/local -xzf go1.4.2.linux-amd64.tar.gz
----

Set GOPATH and PATH:

For Go to work properly, you need to set the following two environment variables:

Setup a go folder:
----
mkdir -p ~/go; echo "export GOPATH=$HOME/go" >> ~/.bashrc
----

Update your path:
----
echo "export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin" >> ~/.bashrc
----

Read the environment variables into current session:
----
source ~/.bashrc
----

install required libs for get build:
----
sudo apt-get install -y build-essential libgmp3-dev
----

clone geth:
----
git clone https://github.com/ethereum/go-ethereum
cd go-ethereum
----
enable OpenCL:
----
export GO_OPENCL=true
export GPU_MAX_ALLOC_PERCENT=95
----
build geth:
----
make geth
----

==== ATI/AMD Config

Next install fglrx-updates package:
----
sudo apt-get install fglrx-updates
----

Downloaded
http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/[AMDAPPSDK 3.0]

Extract it to /opt/AMDAPPSDK-3.0 then:
----
ln -sf /opt/AMDAPPSDK-3.0 /opt/AMDAPP
ln -s /opt/AMDAPP/include/CL /usr/include
ln -sf /opt/AMDAPP/include/CL /usr/include
sudo ln -sf /opt/AMDAPP/include/CL /usr/include
sudo ln -sf /opt/AMDAPP/lib/x86_64/* /usr/lib/
ldconfig
sudo ldconfig
sudo reboot
----

Bust an aticonfig init to generate a new xorg.conf
----
sudo aticonfig --initial -f --adapter=all
----

==== FGLRX Issues
Still had issues with gpu mining in geth and it turns out that I had remnants from a previous fglrx install that was causing issues:

Figure out what is hangining around
----
sudo dpkg -l fglrx*
----

Purge the old 
----
sudo dpkg -P fglrx fglrx-amdcccle fglrx-core fglrx-updates-core fglrx-updates fglrx-amdcccle-updates
----

Verify it is uninstalled:
----
sudo dpkg -l fglrx*
----

Next install fglrx-updates package:
----
sudo apt-get install fglrx-updates
----


==== AMD/ATI Issues

I noticed that I couldn’t do:
----
aticonfig --odsc=<clock speed,mem speed> --adapter=all.  
----
it would only work for first adapter.  Also, I noticed that xorg.conf is overwritten on reboot.  

Turns out that gnu-manager is taking precedence over aticonfig.  To fix this:

I edited /etc/init/gpu-manager.conf so that it now contains:

----
#start on (starting lightdm
#          or starting kdm
#          or starting xdm
#          or starting lxdm)
task
exec gpu-manager --log /var/log/gpu-manager.log
----