= Ethereum Notes
:author: jonny rhea
:doctype: notes
:encoding: utf-8
:lang: en
:toc: left
:published_at: 2015-12-12
:numbered:

[index]
== Mining Rig Setup

I opted to update the OS on my old rigs that used to mine Scrypt/Scrypt-N coins.  Probably wasn't the easiest route, but you never learn anything if nothing goes wrong!  Remember kids, this is supposed to be fun!

=== Update to Xubuntu 14.04

Updated old alt coin mining rig from Xubuntu 12.10 to 13.10

Update /etc/apt/sources.list to EOL sources list:
----
## EOL upgrade sources.list
deb http://old-releases.ubuntu.com/ubuntu/ quantal main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ quantal-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ quantal-security main restricted universe multiverse
----

Installed aptitude:
----
sudo apt-get install aptitude
----

install update manager packages (might already be there):
----
sudo aptitude install update-manager-core update-manager
----

double check desktop package name (should be obvious considerin I am running Xubuntu:
----
dpkg -l | grep tu-desktop
----

installing xubuntu desktop:
----
sudo aptitude install xubuntu-desktop
----

now upgrade:
----
sudo apt-get update
sudo apt-get dist-upgrade
sudo do-release-upgrade
----

Then upgraded to 14.04 so I could use the Ethereum PPAs

=== Build Geth

Download the latest Go:
----
curl -O https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
----

Unpack:
----
tar -C /usr/local -xzf go1.4.2.linux-amd64.tar.gz
----

Set GOPATH and PATH:

For Go to work properly, you need to set the following two environment variables:

Setup a go folder:
----
mkdir -p ~/go; echo "export GOPATH=$HOME/go" >> ~/.bashrc
----

Update your path:
----
echo "export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin" >> ~/.bashrc
----

Read the environment variables into current session:
----
source ~/.bashrc
----

install required libs for get build:
----
sudo apt-get install -y build-essential libgmp3-dev
----

clone geth:
----
git clone https://github.com/ethereum/go-ethereum
cd go-ethereum
----
enable OpenCL:
----
export GO_OPENCL=true
export GPU_MAX_ALLOC_PERCENT=95
----
build geth:
----
make geth
----

=== ATI/AMD Config

Next install fglrx-updates package:
----
sudo apt-get install fglrx-updates
----

Downloaded
http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/[AMDAPPSDK 3.0]

Extract it to /opt/AMDAPPSDK-3.0 then:
----
ln -sf /opt/AMDAPPSDK-3.0 /opt/AMDAPP
ln -s /opt/AMDAPP/include/CL /usr/include
ln -sf /opt/AMDAPP/include/CL /usr/include
sudo ln -sf /opt/AMDAPP/include/CL /usr/include
sudo ln -sf /opt/AMDAPP/lib/x86_64/* /usr/lib/
ldconfig
sudo ldconfig
sudo reboot
----

Bust an aticonfig init to generate a new xorg.conf
----
sudo aticonfig --initial -f --adapter=all
----

=== FGLRX Issues
Still had issues with gpu mining in geth and it turns out that I had remnants from a previous fglrx install that was causing issues:

Figure out what is hangining around
----
sudo dpkg -l fglrx*
----

Purge the old 
----
sudo dpkg -P fglrx fglrx-amdcccle fglrx-core fglrx-updates-core fglrx-updates fglrx-amdcccle-updates
----

Verify it is uninstalled:
----
sudo dpkg -l fglrx*
----

Next install fglrx-updates package:
----
sudo apt-get install fglrx-updates
----


=== AMD/ATI Issues

I noticed that I couldn’t do:
----
aticonfig --odsc=<clock speed,mem speed> --adapter=all.  
----
it would only work for first adapter.  Also, I noticed that xorg.conf is overwritten on reboot.  

Turns out that gnu-manager is taking precedence over aticonfig.  To fix this:

I edited /etc/init/gpu-manager.conf so that it now contains:

----
#start on (starting lightdm
#          or starting kdm
#          or starting xdm
#          or starting lxdm)
task
exec gpu-manager --log /var/log/gpu-manager.log
----

=== Wireless Networking Issues

I was getting tons of connectivity issues when connected to mining pools AND my own ad hoc mining pool at home.  The errors looked like this:

****
  ✘  02:16:02.895|ethminer  Failed to submit hashrate.
  ✘  02:16:02.896|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out
****

Two of my rigs are using wireless networking usb sticks and rather than running ethernet cables into my garage where those two rigs are running, I opted to tweak the wireless settings:

*Basic info:* Check the basic settings by runing this command.

----
$ iwconfig wlan1
----

*Fragment packets:*
This hurts throughput, but makes the packets much more likely to be delivered:
----
$ sudo iwconfig wlan1 frag 256
----

*Enable rts handshaking:* Before sending a packet, handshake with the AP to guarantee that it is listening. This really hurts your throughput but does wonders for getting the attention of the access point. The default is to only perform the handshake on packets bigger than 2kB. The following command forces it for all packets:

----
$ sudo iwconfig wlan1 rts 1
----

*Increase number of retries:* Seven is the default retry value. Set it to thirty by running this command:

----
$ sudo iwconfig wlan1 retry 30
----

[index]
== geth commands
log into the console and hide messages:
----
$ geth console 2>>geth.log
----
log into console and print messages to screen:
----
$ geth console
----

create a second session and attach to the first so you can ignore messages:
----
$ geth attach
----

sync with blockchain (fast):
----
$ geth --fast
----

start GPU mining with geth (multi gpu, autogen DAG, set address, open console):
----
$ geth --mine --minergpus "0,1,2" --autodag --etherbase "0x9884780af266ef60e9f101fe614a00332c6436be" console
----

start geth as an rpc node so other ethminer's can connect:
----
$ geth --maxpeers '100' --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --autodag --rpcapi "db,eth,net,web3,miner" console
----

run get without syncing db:
----
$ geth --maxpeers "0" console
----

import account from another machine:
1)  copy keystone dir (or file) into ~/.ethereum/keystore
----
scp -r ~/.ethereum/keystore user@machine:~/.ethereum
----

2) unlock account:
----
$ geth --unlock=0x00000000000000000000000000000
$ geth account import ~/.ethereum/keystore/file 
----
* You will have to enter your passphrase

create a passphrase:
----
> personal.newAccount("luke i am your father")
----

view all accounts:
----
> web3.eth.accounts
----

get the balance of a specific account:
----
> web3.fromWei(eth.getBalance(web3.eth.accounts[0]), "ether")
----

ensure your rig is mining to your address:
----
> web3.eth.coinbase
----

if the command above returns "0x0" then your are mining into a black hole.  fix this by running this command:
----
> web3.miner.setEtherbase(web3.eth.accounts[0])
----

get balance of account your are mining into:

----  
> web3.fromWei(eth.getBalance(eth.coinbase), "ether")
----

check hashrate:

----
> miner.hashrate
----

figure out current block that you have sync’d to:

----
> web3.eth.syncing.currentBlock
----

highest block:
----
> web3.eth.syncing.highestBlock
----

Get block info:
----
> web3.eth.getBlock(web3.eth.blockNumber);
----

Get block difficulty:
----
> web3.eth.getBlock(web3.eth.blockNumber).difficulty
----

load a script from a file:
----
> loadScript("/home/user/foo.js”)
----

[index]
== ethminer commands

Start mining with ethminer (geth is running locally):
----
$ ethminer --farm-recheck 100 --no-precompute -G -F http://127.0.0.1:8545
----

Start mining with ethminer (geth is running on another machine):
----
$ ethminer --farm-recheck 100 --no-precompute -G -F http://192.168.1..105:8545
----


[index]
== aticonfig commands

check gpu temp:
----
$ aticonfig --adapter=all --odgt
----

check gpu clock speed:
----
$ aticonfig --adapter=all --odgc
----

enable overdrive:
----
$ aticonfig --od-enable
----

set clockspeed:
----
$ aticonfig --adapter=all --odsc=<gpu speed,memory speed>
----

get fanspeed for GPU N:
----
$ env DISPLAY=:0.N aticonfig --pplib-cmd "get fanspeed 0"
----

set fanspeed X for GPU N:
----
$ env DISPLAY=:0.N aticonfig --pplib-cmd "set fanspeed 0 X”
----

continuously monitor gpu temp and load:
----
$ watch -n 3 aticonfig --adapter=ALL --odgt --odgc 
----