= Notes
:author: jonny rhea
:doctype: notes
:encoding: utf-8
:lang: en
:toc: left
:date: 5/12/2013
:numbered:

[index]
== general commands
=== find
Search the current dir (and below) for a file named sue:
[source,bash]
$ find . –name sue

Search /tmp and /var for files named foo*bar modified in the last week:  
[source,bash]
$ find /tmp /var –mtime -7 -name foo\*bar

Search the file system for files modified < 10 mins ago, excluding dirs and other special files:
[source,bash]
$ find / -mmin -10 –type f

[index]
== linux system info

report file system disk space usage (human readable):
[source,bash]
$ df -h

processor info:
[source,bash]
$ more /proc/cpuinfo

memory info:
[source,bash]
$ more /proc/meminfo

check to see if Linux is 32 or 64bit:
[source,bash]
$ getconf LONG_BIT

distribution info:
[source,bash]
$ lsb_release

list all packages installed:
[source,bash]
$ dpkg -l

find the 25 largest dirs starting at the current dir:
[source,bash]
$ du –xk |sort –n |tail -25

show what processes are using which ports:
[source,bash]
$ netstat -tulpn

[index]
== linux system configuration
check and repair filesystem:
[source,bash]
$ fsck /dev/sda1

change the frequency of filesys checks on startup:
[source,bash]
$ tune2fs –c <some number> /dev/sda1

to change the login manager edit:
****
*/etc/X11/default-display-manager*
****

if your mac address changes edit or delete:
****
*/etc/udev/rules.d/70-persistent-net.rules*
****

disable filesys checks by changing the last number in line to 0:
****
*/etc/fstab*
----
# <file system> <mount point>   <type>  <options>     <dump> <pass>+
# performs filesys check every 30 startups
/dev/sda1        /mnt/foo        ext4   defaults 0 30   
# filesys checks disabled
/dev/sdb1        /mnt/bar        ext4   defaults 0 0
----
****

To grant passwordless rsh:
****
*hosts.equiv* +
----
<computer name> <user name>
----
****
Create ssh key (rsa):
----
$ cd ~/.ssh
$ ssh-keygen –t rsa
$ ssh-add <file>
----
[index]
== linux binutils
=== objdump
*display info from an object file(s).*

basic syntax:
[source,bash]
$ objdump <options> file

display the contents of the overall file header:
[source,bash]
----
$ objdump –f foo

foo:     file format elf32-i386
architecture: i386, flags 0x00000112:
EXEC_P, HAS_SYMS, D_PAGED
start address 0x0804be34
----

display object format specific file header contents:
[source,bash]
----
$ objdump -p foo

foo:     file format elf32-i386

Program Header:
    PHDR off    0x00000034 vaddr 0x08048034 paddr 0x08048034 align 2**2
         filesz 0x00000120 memsz 0x00000120 flags r-x
  INTERP off    0x00000154 vaddr 0x08048154 paddr 0x08048154 align 2**0
         filesz 0x00000013 memsz 0x00000013 flags r--
(...)
Dynamic Section:
  NEEDED               libc.so.6
  INIT                 0x080494a0
  FINI                 0x0805a02c
  GNU_HASH             0x080481ac
  STRTAB               0x080489b8
(...)
Version References:
  required from libc.so.6:
    0x09691f73 0x00 10 GLIBC_2.1.3
    0x0d696912 0x00 09 GLIBC_2.2
    0x09691a73 0x00 07 GLIBC_2.2.3
(...)
----

=== nm
*provides info on the symbols used in an object file or executable. by default, nm shows the symbol: value, type and name.*

basic syntax:
[source,bash]
$ nm 

[NOTE]
====
if no file is provided, nm will inspect a.out
====

display default information on executable (or object file):
[source,bash]
$ nm foo

display all the symbols in an executable:
[source,bash]
$ nm -n foo

display information about the size of a particular symbol, bar:
[source,bash]
$ nm -n foo -S | grep bar

only display information on external symbols:
[source,bash]
$ nm -g foo

[index]
== other utils
=== file
*get basic file information on a file(s).*

basic syntax:
[source, bash]
$ file file

example:
[source,bash]
----
$ file foo

foo: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, stripped
----
